framework: bump jsonschema crate to v0.17
So that it can compile without failing on
error[E0635]: unknown feature `stdsimd`
  --> .cargo/registry/src/index.crates.io-6f17d22bba15001f/ahash-0.7.6/src/lib.rs:33:42
   |
33 | #![cfg_attr(feature = "stdsimd", feature(stdsimd))]
   |                                          ^^^^^^^